version: '3.3'

services:
  db:
    env_file:
      - .env
    image: postgres:10.10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_DBNAME}
    healthcheck:
      test: exit 0

  app:
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    expose:
      - 3000
    build: .
    depends_on:
      - db
    entrypoint: ./app_dev.sh

  worker:
    env_file:
      - .env
    build: .
    depends_on:
      - app
    command: python3 manage.py qcluster