# Generated by Django 2.2.3 on 2019-07-04 10:20

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=64)),
                ('chinese_name', models.CharField(max_length=16)),
                ('twitter_id', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64, verbose_name='Access Token')),
                ('access_token_expired_at', models.DateTimeField(null=True, verbose_name='Access Token 过期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_buzzbird', models.BooleanField(default=False, verbose_name='Published to buzzbird Weibo?')),
                ('is_discourse', models.BooleanField(default=False, verbose_name='Published to discourse?')),
                ('media_url', models.URLField(max_length=1024, null=True)),
                ('link', models.URLField(db_index=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('type', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=16)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.Member')),
            ],
        ),
    ]
