# Generated by Django 2.2.9 on 2020-01-15 09:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_buzzbird', models.BooleanField(default=False, verbose_name='Published to buzzbird Weibo?')),
                ('is_discourse', models.BooleanField(default=False, verbose_name='Published to discourse?')),
                ('is_video', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, db_index=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('type', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('instagram_v2', 'Instagram V2'), ('weibo', 'Weibo')], max_length=16)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('status_id', models.CharField(blank=True, db_index=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('original_url', models.URLField(max_length=1024)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='core.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64, verbose_name='Access Token')),
                ('access_token_expired_at', models.DateTimeField(null=True, verbose_name='Access Token 过期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=64)),
                ('chinese_name', models.CharField(max_length=16)),
                ('instagram_id', models.CharField(blank=True, max_length=64)),
                ('twitter_id', models.CharField(blank=True, max_length=128)),
                ('weibo_id', models.CharField(blank=True, max_length=64)),
                ('archived', models.BooleanField(default=False)),
                ('avatar', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Media')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.Member'),
        ),
    ]
