# Generated by Django 2.2.9 on 2020-01-16 02:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(blank=True, db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='feed',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='feed',
            name='status_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
