# Generated by Django 2.1.2 on 2018-10-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=128, unique=True, verbose_name='用户推特 ID')),
                ('english_name', models.CharField(max_length=64, verbose_name='英文名')),
                ('chinese_name', models.CharField(max_length=16, null=True, verbose_name='中文译名')),
            ],
        ),
    ]
