# Generated by Django 2.2.3 on 2019-07-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=512, null=True)),
                ('original_url', models.URLField(max_length=1024)),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='core.Feed')),
            ],
        ),
    ]
