# Generated by Django 2.2.3 on 2019-07-11 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2019, 7, 11)),
            preserve_default=False,
        ),
    ]
