# Generated by Django 2.2.12 on 2020-08-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200116_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='synced_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
