# Generated by Django 2.2.3 on 2019-07-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_media_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='status_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
