# Generated by Django 2.2.3 on 2019-07-18 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feed_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Media'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='status_id',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter'), ('instagram_v2', 'Instagram V2')], max_length=16),
        ),
    ]
