# Generated by Django 2.2 on 2019-04-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instagram_instagrammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='media_url',
            field=models.URLField(max_length=1024),
        ),
    ]
