# Generated by Django 2.2 on 2019-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190411_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='is_discourse',
            field=models.BooleanField(default=False, verbose_name='Published to discourse?'),
        ),
    ]
