# Generated by Django 2.2 on 2019-04-27 04:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_instagram_is_discourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagram',
            old_name='published_at',
            new_name='created_at',
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_buzzbird', models.BooleanField(default=False, verbose_name='Published to buzzbird Weibo?')),
                ('is_discourse', models.BooleanField(default=False, verbose_name='Published to discourse?')),
                ('media_url', models.URLField(max_length=1024)),
                ('link', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(verbose_name='Published on Twitter at')),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.TwitterMember')),
            ],
        ),
    ]
