# Generated by Django 2.2.5 on 2019-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190809_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
