# Generated by Django 2.2.3 on 2019-07-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190427_0425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramMember',
            new_name='Member',
        ),
    ]
