# Generated by Django 2.2.9 on 2020-01-15 07:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_member_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(blank=True, db_index=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='status_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram_id',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter_id',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='weibo_id',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
