# Generated by Django 2.2.3 on 2019-07-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190702_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Twitter',
        ),
        migrations.DeleteModel(
            name='TwitterMember',
        ),
    ]
