# Generated by Django 2.2.3 on 2019-07-02 12:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190702_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('is_buzzbird', models.BooleanField(default=False, verbose_name='Published to buzzbird Weibo?')),
                ('is_discourse', models.BooleanField(default=False, verbose_name='Published to discourse?')),
                ('media_url', models.URLField(max_length=1024)),
                ('link', models.URLField(db_index=True)),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=1024)),
                ('type', models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=16)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            managers=[
                ('instagram', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('instagram', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='twitter_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter')], default='instagram', max_length=16),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Instagram',
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.Member'),
        ),
    ]
