# Generated by Django 2.2.3 on 2019-07-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190702_1245'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='feed',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
    ]
