# Generated by Django 2.2.3 on 2019-07-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190702_1426_squashed_0014_auto_20190702_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='english_name',
            field=models.CharField(max_length=64),
        ),
    ]
