# Generated by Django 2.2.3 on 2019-07-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190702_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='type',
        ),
        migrations.AlterField(
            model_name='member',
            name='english_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
